
title: Dhrubajyoti Chakraborty
description: Researcher in Economics, Bounded Rationality, and Social Network Analysis
baseurl: ""
url: "https://yourusername.github.io"
theme: minima

# Social Links
github_username: yourusername
email: your-email@example.com
