
title: Dhrubajyoti Chakraborty
description: Researcher in Economics, Bounded Rationality, and Social Network Analysis
baseurl: ""
url: "https://dhruba-c.github.io"
theme: minima

# Social Links
github_username: dhruba-c
email: dhrubajyoti.chakraborty_phd23@ashoka.edu.in
